version: "3.8"

services:
  playwright:
    build: .
    image: mytest:latest
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - .:/app
    command: ["pytest", "-s", "-q"]
