services:
  playwright:
    build: .
    image: mytest:latest
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - .:/app
    command: ["pytest", "-s", "-q"]
    environment:
      - LOGIN_EMAIL=${FG_ID}
      - LOGIN_PASSWORD=${FG_PW}
